/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --types --keepnames --keepgroups --keepmeshes --keepmaterials /Users/pedrolimasilva/Dev/BionicleIdleRpg/public/bohrok_master.glb 
Files: /Users/pedrolimasilva/Dev/BionicleIdleRpg/public/bohrok_master.glb [5.11MB] > /Users/pedrolimasilva/Dev/BionicleIdleRpg/bohrok_master-transformed.glb [435.26KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Attack' | 'Ball' | 'BohrokAction' | 'Flying' | 'Flying Pose' | 'Hit' | 'Hit.001' | 'Idle'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['Part-41671p01_dot_dat003']: THREE.Mesh
    ['Part-41671p01_dot_dat003_1']: THREE.Mesh
    Krana_Cradle_1: THREE.Mesh
    Krana: THREE.Mesh
    Head_1: THREE.Mesh
    Object186: THREE.Mesh
    Object171: THREE.Mesh
    Object183: THREE.Mesh
    Object172: THREE.Mesh
    Object175: THREE.Mesh
    Cube002: THREE.Mesh
    Object181: THREE.Mesh
    Cube003: THREE.Mesh
    Object176: THREE.Mesh
    Object180: THREE.Mesh
    Object179: THREE.Mesh
    Neck_1: THREE.Mesh
    Neck_2_1: THREE.Mesh
    Foot_L_1: THREE.Mesh
    Leg_L_1: THREE.Mesh
    Hip_L_1: THREE.Mesh
    HandL: THREE.Mesh
    GahlokL: THREE.Mesh
    KohrakL: THREE.Mesh
    LehvakL: THREE.Mesh
    NuhvokL: THREE.Mesh
    PahrakL: THREE.Mesh
    TahnokL: THREE.Mesh
    Arm_L_1: THREE.Mesh
    Shoulder_L_1: THREE.Mesh
    Foot_R_1: THREE.Mesh
    Leg_R_1: THREE.Mesh
    Hip_R_1: THREE.Mesh
    HandR: THREE.Mesh
    GahlokR: THREE.Mesh
    KohrakR: THREE.Mesh
    NuhvokR: THREE.Mesh
    PahrakR: THREE.Mesh
    TahnokR: THREE.Mesh
    LehvakR: THREE.Mesh
    Arm_R_1: THREE.Mesh
    Shoulder_R_1: THREE.Mesh
    Body_1: THREE.Mesh
    Object173: THREE.Mesh
    Object184: THREE.Mesh
    Object187: THREE.Mesh
    Object190: THREE.Mesh
    Object165: THREE.Mesh
    Object182: THREE.Mesh
    Object451: THREE.Mesh
  }
  materials: {
    Bohrok_Main: THREE.MeshStandardMaterial
    ['TRANS-CLEAR']: THREE.MeshStandardMaterial
    Solid_Light_Grey: THREE.MeshStandardMaterial
    Krana: THREE.MeshStandardMaterial
    Solid_Black: THREE.MeshStandardMaterial
    Bohrok_Eye: THREE.MeshStandardMaterial
    Bohrok_Iris: THREE.MeshStandardMaterial
    ['Bohrok Teeth']: THREE.MeshStandardMaterial
    Bohrok_Secondary: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/bohrok_master-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Bohrok" position={[0, 0.157, -0.072]} scale={0.128}>
          <group name="Body" rotation={[1.467, 0, 0]}>
            <group name="Neck" position={[0, 0.986, 0]} rotation={[-1.903, 0, 0]}>
              <group name="Head" position={[0, 0.844, 0]} rotation={[2.824, 0, 0]}>
                <group name="Face_Plate" position={[0, 0.91, 0]} rotation={[-1.868, 0, 0]}>
                  <group name="Face_Plate_1" position={[0, 0.001, -0.001]} rotation={[1.575, 0, 3.142]} scale={-0.008}>
                    <mesh name="Part-41671p01_dot_dat003" geometry={nodes['Part-41671p01_dot_dat003'].geometry} material={materials.Bohrok_Main} />
                    <mesh name="Part-41671p01_dot_dat003_1" geometry={nodes['Part-41671p01_dot_dat003_1'].geometry} material={materials['TRANS-CLEAR']} />
                  </group>
                </group>
                <group name="Krana_Cradle" position={[0, 0.47, -0.188]} rotation={[2.984, 0, 0]}>
                  <mesh name="Krana_Cradle_1" geometry={nodes.Krana_Cradle_1.geometry} material={materials.Solid_Light_Grey} position={[-0.001, 0.302, -0.157]} rotation={[2.919, 0, 3.142]} scale={-0.008}>
                    <mesh name="Krana" geometry={nodes.Krana.geometry} material={materials.Krana} position={[-2.31, 10.77, 13.877]} rotation={[1.134, 0, 0]} scale={0.999} />
                  </mesh>
                </group>
                <mesh name="Head_1" geometry={nodes.Head_1.geometry} material={materials.Solid_Black} position={[0, -0.001, 0]} rotation={[-0.38, 0, 0]} scale={-0.008}>
                  <mesh name="Object186" geometry={nodes.Object186.geometry} material={materials.Solid_Black} position={[-0.002, 40.851, 0.001]} />
                  <mesh name="Object171" geometry={nodes.Object171.geometry} material={materials.Solid_Black} position={[20.081, -81.592, -20.425]} rotation={[0, Math.PI / 2, 0]} scale={[1.017, 1.019, 0.992]} />
                  <mesh name="Object183" geometry={nodes.Object183.geometry} material={materials.Solid_Black} position={[-20.084, -81.592, -20.433]} rotation={[0, Math.PI / 2, 0]} scale={[1.017, 1.019, 0.992]} />
                  <mesh name="Object172" geometry={nodes.Object172.geometry} material={materials.Solid_Light_Grey} position={[0, -102.128, -40.851]} scale={[1, 1.005, 1.005]} />
                  <mesh name="Object175" geometry={nodes.Object175.geometry} material={materials.Bohrok_Eye} position={[-40.167, -61.338, -0.061]} rotation={[-2.356, -1.571, 0]} scale={[1.007, 1.017, 0.992]}>
                    <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Bohrok_Iris} position={[-0.402, 25.415, -2.942]} rotation={[1.537, 0.019, -3.096]} scale={[-10.411, -10.397, -25.479]} />
                  </mesh>
                  <mesh name="Object181" geometry={nodes.Object181.geometry} material={materials.Bohrok_Eye} position={[40.167, -61.338, -0.062]} rotation={[-2.356, Math.PI / 2, 0]} scale={[1.007, 1.017, 0.992]}>
                    <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Bohrok_Iris} position={[-0.154, 25.465, -3.938]} rotation={[1.6, 0.02, 3.023]} scale={[-10.411, -10.397, -25.479]} />
                  </mesh>
                  <mesh name="Object176" geometry={nodes.Object176.geometry} material={materials['Bohrok Teeth']} position={[-20.084, -102.04, -40.788]} rotation={[Math.PI / 2, 0, 0]} scale={[0.992, 1.015, 1.017]} />
                  <mesh name="Object180" geometry={nodes.Object180.geometry} material={materials['Bohrok Teeth']} position={[20.084, -102.039, -40.788]} rotation={[Math.PI / 2, 0, 0]} scale={[0.992, 1.015, 1.017]} />
                  <mesh name="Object179" geometry={nodes.Object179.geometry} material={materials.Solid_Black} position={[0, -61.276, 0]} rotation={[Math.PI / 4, 0, -Math.PI]} scale={[1.002, 1, 1]} />
                </mesh>
              </group>
              <mesh name="Neck_1" geometry={nodes.Neck_1.geometry} material={materials.Solid_Light_Grey} position={[0, 0.423, 0]} rotation={[-3.142, 0, Math.PI / 2]} scale={-0.008} />
            </group>
            <group name="Neck_2" position={[0, 0.696, -0.174]} rotation={[-1.903, 0, 0]}>
              <mesh name="Neck_2_1" geometry={nodes.Neck_2_1.geometry} material={materials.Solid_Light_Grey} position={[0, 0.423, 0]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={-0.008} />
            </group>
            <group name="Hip_L" position={[0.423, 0.001, 0]} rotation={[-2.601, 0, -Math.PI]}>
              <group name="Leg_L" position={[0, 0.338, -0.001]} rotation={[2.356, 0, Math.PI]}>
                <group name="Foot_L" position={[0, 0.715, 0]} rotation={[-0.436, 0, 0]}>
                  <mesh name="Foot_L_1" geometry={nodes.Foot_L_1.geometry} material={materials.Bohrok_Main} position={[0, 0.001, 0.001]} rotation={[-0.785, 0, Math.PI]} scale={-0.008} />
                </group>
                <mesh name="Leg_L_1" geometry={nodes.Leg_L_1.geometry} material={materials.Bohrok_Secondary} position={[0, 0.715, 0]} rotation={[2.356, Math.PI / 2, 0]} scale={-0.008} />
              </group>
              <mesh name="Hip_L_1" geometry={nodes.Hip_L_1.geometry} material={materials.Solid_Black} position={[0, 0.168, 0]} rotation={[3.142, 1.571, 0]} scale={-0.008} />
            </group>
            <group name="Shoulder_L" position={[0.423, -0.058, -0.233]} rotation={[2.111, 0, -Math.PI]}>
              <group name="Arm_L" position={[-0.001, 0.337, -0.001]} rotation={[-0.507, -0.785, 1.583]}>
                <group name="Shield_L" position={[0, 0.715, 0]} rotation={[-0.782, 0, 0.095]}>
                  <mesh name="HandL" geometry={nodes.HandL.geometry} material={materials.Solid_Black} position={[0, 0.17, 0]} rotation={[0.022, -1.562, 0.025]} scale={-0.008}>
                    <mesh name="GahlokL" geometry={nodes.GahlokL.geometry} material={materials.Bohrok_Main} position={[0.09, -40.168, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="KohrakL" geometry={nodes.KohrakL.geometry} material={materials.Bohrok_Main} position={[-0.071, -37.718, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="LehvakL" geometry={nodes.LehvakL.geometry} material={materials.Bohrok_Main} position={[-0.327, -36.152, 0]} rotation={[0, -1.571, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="NuhvokL" geometry={nodes.NuhvokL.geometry} material={materials.Bohrok_Main} position={[0.146, -39.667, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="PahrakL" geometry={nodes.PahrakL.geometry} material={materials.Bohrok_Main} position={[-0.111, -36.007, 0]} rotation={[0, -1.571, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="TahnokL" geometry={nodes.TahnokL.geometry} material={materials.Bohrok_Main} position={[-0.327, -40.421, 0]} rotation={[0, -1.571, 0]} scale={[1.01, 1.002, 1]} />
                  </mesh>
                </group>
                <mesh name="Arm_L_1" geometry={nodes.Arm_L_1.geometry} material={materials.Bohrok_Secondary} position={[0, 0.715, 0]} rotation={[0.001, -1.559, 2.357]} scale={-0.008} />
              </group>
              <mesh name="Shoulder_L_1" geometry={nodes.Shoulder_L_1.geometry} material={materials.Solid_Black} position={[0, 0.168, 0]} rotation={[-3.142, 1.571, 0]} scale={-0.008} />
            </group>
            <group name="Hip_R" position={[-0.423, 0.001, 0]} rotation={[-2.601, 0, Math.PI]}>
              <group name="Leg_R" position={[0, 0.338, -0.001]} rotation={[2.356, 0, -Math.PI]}>
                <group name="Foot_R" position={[0, 0.715, 0]} rotation={[-0.436, 0, 0]}>
                  <mesh name="Foot_R_1" geometry={nodes.Foot_R_1.geometry} material={materials.Bohrok_Main} position={[0, 0.001, 0.001]} rotation={[-0.785, 0, -Math.PI]} scale={-0.008} />
                </group>
                <mesh name="Leg_R_1" geometry={nodes.Leg_R_1.geometry} material={materials.Bohrok_Secondary} position={[0, 0.715, 0]} rotation={[2.356, Math.PI / 2, 0]} scale={-0.008} />
              </group>
              <mesh name="Hip_R_1" geometry={nodes.Hip_R_1.geometry} material={materials.Solid_Black} position={[0, 0.168, 0]} rotation={[3.142, 1.571, 0]} scale={-0.008} />
            </group>
            <group name="Shoulder_R" position={[-0.423, -0.058, -0.233]} rotation={[2.111, 0, Math.PI]}>
              <group name="Arm_R" position={[0.001, 0.337, -0.001]} rotation={[-0.507, 0.785, -1.583]}>
                <group name="Shield_R" position={[0, 0.715, 0]} rotation={[-0.782, 0, -0.095]}>
                  <mesh name="HandR" geometry={nodes.HandR.geometry} material={materials.Solid_Black} position={[0, 0.17, 0]} rotation={[0.022, 1.562, -0.025]} scale={-0.008}>
                    <mesh name="GahlokR" geometry={nodes.GahlokR.geometry} material={materials.Bohrok_Main} position={[0.339, -40.168, 0]} rotation={[0, 1.571, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="KohrakR" geometry={nodes.KohrakR.geometry} material={materials.Bohrok_Main} position={[0.178, -37.717, 0]} rotation={[0, Math.PI / 2, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="NuhvokR" geometry={nodes.NuhvokR.geometry} material={materials.Bohrok_Main} position={[0.138, -39.667, -0.001]} rotation={[0, 1.571, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="PahrakR" geometry={nodes.PahrakR.geometry} material={materials.Bohrok_Main} position={[0.138, -36.007, -0.001]} rotation={[0, Math.PI / 2, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="TahnokR" geometry={nodes.TahnokR.geometry} material={materials.Bohrok_Main} position={[0.327, -40.421, 0.001]} rotation={[0, 1.571, 0]} scale={[1.01, 1.002, 1]} />
                    <mesh name="LehvakR" geometry={nodes.LehvakR.geometry} material={materials.Bohrok_Main} position={[1.617, -36.151, -0.001]} rotation={[0, Math.PI / 2, 0]} scale={[1.01, 1.002, 1]} />
                  </mesh>
                </group>
                <mesh name="Arm_R_1" geometry={nodes.Arm_R_1.geometry} material={materials.Bohrok_Secondary} position={[0, 0.715, 0]} rotation={[-3.141, -1.559, -0.784]} scale={-0.008} />
              </group>
              <mesh name="Shoulder_R_1" geometry={nodes.Shoulder_R_1.geometry} material={materials.Solid_Black} position={[0, 0.168, 0]} rotation={[-3.142, 1.571, 0]} scale={-0.008} />
            </group>
            <mesh name="Body_1" geometry={nodes.Body_1.geometry} material={materials.Solid_Black} rotation={[2.111, 0, -Math.PI]} scale={-0.008}>
              <mesh name="Object173" geometry={nodes.Object173.geometry} material={materials.Solid_Black} position={[0, -61.276, 102.127]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.998, 1, 1]} />
              <mesh name="Object184" geometry={nodes.Object184.geometry} material={materials.Solid_Black} position={[0, -61.276, 61.276]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.998, 1, 1]} />
              <mesh name="Object187" geometry={nodes.Object187.geometry} material={materials.Solid_Black} position={[0, -20.426, -20.426]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh name="Object190" geometry={nodes.Object190.geometry} material={materials.Solid_Black} position={[0, -61.276, -0.001]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.998, 1, 1]} />
              <mesh name="Object165" geometry={nodes.Object165.geometry} material={materials.Solid_Light_Grey} position={[0, -61.19, -0.004]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.019, 0.996, 1.017]} />
              <mesh name="Object182" geometry={nodes.Object182.geometry} material={materials.Bohrok_Main} position={[-20.042, -61.178, 40.85]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.996, 1.019, 1.018]} />
              <mesh name="Object451" geometry={nodes.Object451.geometry} material={materials.Bohrok_Main} position={[19.901, -61.178, 40.85]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.996, 1.019, 1.018]} />
            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bohrok_master-transformed.glb')
