/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --types --keepnames --keepgroups --keepmeshes --keepmaterials /Users/pedrolimasilva/Dev/BionicleIdleRpg/public/toa_pohatu_mata.glb 
Files: /Users/pedrolimasilva/Dev/BionicleIdleRpg/public/toa_pohatu_mata.glb [7.58MB] > /Users/pedrolimasilva/Dev/BionicleIdleRpg/toa_pohatu_mata-transformed.glb [990.1KB] (87%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Attack' | 'Hit' | 'Idle' | 'Idle.001' | 'Idle.002' | 'PohatuAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object007: THREE.Mesh
    Object008: THREE.Mesh
    Object009: THREE.Mesh
    Object046: THREE.Mesh
    ['Part-evanetic__kit2-8_dot_1_dot_dat002']: THREE.Mesh
    ['Part-evanetic__kit2-8_dot_1_dot_dat002_1']: THREE.Mesh
    ['Part-evanetic__kit2-8_dot_1_dot_dat002_2']: THREE.Mesh
    Object047: THREE.Mesh
    Object045: THREE.Mesh
    Object038: THREE.Mesh
    Object039: THREE.Mesh
    Object040: THREE.Mesh
    Object010: THREE.Mesh
    Object037: THREE.Mesh
    Object036: THREE.Mesh
    Object012: THREE.Mesh
    Object013: THREE.Mesh
    Object014: THREE.Mesh
    ['Part-evanetic__kit2-8_dot_1_dot_dat001']: THREE.Mesh
    ['Part-evanetic__kit2-8_dot_1_dot_dat001_1']: THREE.Mesh
    ['Part-evanetic__kit2-8_dot_1_dot_dat001_2']: THREE.Mesh
    Object035: THREE.Mesh
    Object041: THREE.Mesh
    Object042: THREE.Mesh
    Object043: THREE.Mesh
    Object011: THREE.Mesh
    Head_1: THREE.Mesh
    Akaku: THREE.Mesh
    Hau: THREE.Mesh
    Huna: THREE.Mesh
    Kakama: THREE.Mesh
    Kaukau: THREE.Mesh
    Komau: THREE.Mesh
    Mahiki: THREE.Mesh
    Matatu: THREE.Mesh
    Miru: THREE.Mesh
    Pakari: THREE.Mesh
    Rau: THREE.Mesh
    Ruru: THREE.Mesh
    Glowing_Eyes: THREE.Mesh
    Object004: THREE.Mesh
    Object005: THREE.Mesh
    Chest_1: THREE.Mesh
    Object001: THREE.Mesh
    Object002: THREE.Mesh
    Object003: THREE.Mesh
    Body_1: THREE.Mesh
    Object016: THREE.Mesh
    Object018: THREE.Mesh
    ['Part-Evanetic__kit2-3_dot_1_dot_dat001']: THREE.Mesh
    ['Part-Evanetic__kit2-3_dot_1_dot_dat001_1']: THREE.Mesh
    ['Part-Evanetic__kit2-3_dot_1_dot_dat001_2']: THREE.Mesh
    Object020: THREE.Mesh
    Object021: THREE.Mesh
    Object017: THREE.Mesh
    Object022: THREE.Mesh
    ['Part-Evanetic__kit2-4_dot_1_dot_dat001']: THREE.Mesh
    ['Part-Evanetic__kit2-4_dot_1_dot_dat001_1']: THREE.Mesh
    ['Part-Evanetic__kit2-4_dot_1_dot_dat001_2']: THREE.Mesh
    Object006: THREE.Mesh
    Object015: THREE.Mesh
    Object030: THREE.Mesh
    ['Part-Evanetic__kit2-3_dot_1_dot_dat001']: THREE.Mesh
    ['Part-Evanetic__kit2-3_dot_1_dot_dat001_1']: THREE.Mesh
    ['Part-Evanetic__kit2-3_dot_1_dot_dat001_2']: THREE.Mesh
    Object032: THREE.Mesh
    Object033: THREE.Mesh
    Object029: THREE.Mesh
    ['Part-Evanetic__kit2-4_dot_1_dot_dat002']: THREE.Mesh
    ['Part-Evanetic__kit2-4_dot_1_dot_dat002_1']: THREE.Mesh
    ['Part-Evanetic__kit2-4_dot_1_dot_dat002_2']: THREE.Mesh
    Object049: THREE.Mesh
    Object027: THREE.Mesh
    Waist_1: THREE.Mesh
    Object050: THREE.Mesh
    Object051: THREE.Mesh
    Object052: THREE.Mesh
    Object053: THREE.Mesh
    Object054: THREE.Mesh
    Object055: THREE.Mesh
    Object056: THREE.Mesh
    Object057: THREE.Mesh
    Object058: THREE.Mesh
    Object059: THREE.Mesh
    Object060: THREE.Mesh
    ['Part-32475_dot_dat001']: THREE.Mesh
    ['Part-32475_dot_dat001_1']: THREE.Mesh
    ['Part-32560_dot_dat003']: THREE.Mesh
    ['Part-32560_dot_dat003_1']: THREE.Mesh
    ['Part-32475_dot_dat001']: THREE.Mesh
    ['Part-32475_dot_dat001_1']: THREE.Mesh
    ['Part-32560_dot_dat004']: THREE.Mesh
    ['Part-32560_dot_dat004_1']: THREE.Mesh
    Rock: THREE.Mesh
  }
  materials: {
    Solid_Black: THREE.MeshStandardMaterial
    ['Pohatu Rock']: THREE.MeshStandardMaterial
    ['Pohatu_SOLID-TAN']: THREE.MeshStandardMaterial
    Solid_Light_Grey: THREE.MeshStandardMaterial
    ['Pohatu Eyes']: THREE.MeshStandardMaterial
    ['Trans Neon Orange']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/toa_pohatu_mata-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Pohatu" position={[0, 0.241, 0]}>
          <group name="Waist" rotation={[-0.001, 0, 0]}>
            <group name="Body" position={[0, 0.064, 0]} rotation={[0.002, 0, 0]}>
              <group name="Chest" position={[0, 0.021, 0]} rotation={[-0.002, 0, 0]}>
                <group name="Shoulder_L" position={[0.046, 0.023, 0]} rotation={[0, 0, -Math.PI / 2]}>
                  <group name="Arm_Upper_L" position={[0.001, 0.018, -0.022]} rotation={[-1.568, 0, 0]}>
                    <group name="Arm_Lower_L" position={[0, 0.035, 0]} rotation={[1.68, 0, 0]}>
                      <group name="Hand_L" position={[0, 0.101, 0]} rotation={[-0.112, 0, 0]}>
                        <mesh name="Object007" geometry={nodes.Object007.geometry} material={materials.Solid_Black} position={[0, 0, -0.001]} rotation={[0, 0, Math.PI / 2]}>
                          <mesh name="Object008" geometry={nodes.Object008.geometry} material={materials.Solid_Black} position={[0.042, 0.003, -0.021]} />
                          <mesh name="Object009" geometry={nodes.Object009.geometry} material={materials.Solid_Black} position={[0.042, 0.003, 0.022]} />
                        </mesh>
                      </group>
                      <group name="Arm_Piston_Lower_L" position={[0, 0.057, -0.011]} rotation={[-3.131, -0.005, 0.002]}>
                        <mesh name="Object046" geometry={nodes.Object046.geometry} material={materials['Pohatu Rock']} position={[0, 0.013, 0.006]} rotation={[3.019, -0.005, 1.572]} />
                      </group>
                      <group name="Object044" position={[0, 0.049, -0.015]} rotation={[-0.112, 0, Math.PI / 2]}>
                        <mesh name="Part-evanetic__kit2-8_dot_1_dot_dat002" geometry={nodes['Part-evanetic__kit2-8_dot_1_dot_dat002'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                        <mesh name="Part-evanetic__kit2-8_dot_1_dot_dat002_1" geometry={nodes['Part-evanetic__kit2-8_dot_1_dot_dat002_1'].geometry} material={materials.Solid_Light_Grey} />
                        <mesh name="Part-evanetic__kit2-8_dot_1_dot_dat002_2" geometry={nodes['Part-evanetic__kit2-8_dot_1_dot_dat002_2'].geometry} material={materials['Pohatu Rock']} />
                      </group>
                    </group>
                    <group name="Arm_Piston_Upper_L" position={[0, 0.047, 0]} rotation={[1.691, 0, 0]}>
                      <mesh name="Object047" geometry={nodes.Object047.geometry} material={materials.Solid_Light_Grey} position={[0, 0.016, -0.005]} rotation={[-0.123, 0, 1.571]} />
                    </group>
                    <mesh name="Object045" geometry={nodes.Object045.geometry} material={materials['Pohatu_SOLID-TAN']} position={[0, 0.019, -0.014]} rotation={[1.568, 0, Math.PI / 2]} />
                  </group>
                  <mesh name="Object038" geometry={nodes.Object038.geometry} material={materials.Solid_Black} position={[-0.01, 0.017, 0]} rotation={[0, 0, Math.PI / 2]}>
                    <mesh name="Object039" geometry={nodes.Object039.geometry} material={materials.Solid_Black} position={[0.032, -0.011, -0.001]} />
                    <mesh name="Object040" geometry={nodes.Object040.geometry} material={materials.Solid_Black} position={[0.021, -0.011, -0.001]} />
                  </mesh>
                </group>
                <group name="Body_Piston_Upper_L" position={[0.017, 0.005, 0]} rotation={[1.561, -1.309, -1.58]}>
                  <mesh name="Object010" geometry={nodes.Object010.geometry} material={materials['Pohatu Rock']} position={[-0.003, 0.011, 0]} rotation={[-0.004, -1.569, 2.876]} />
                </group>
                <group name="Shoulder_R" position={[-0.045, 0.023, 0]} rotation={[0, 0, Math.PI / 2]}>
                  <group name="Arm_Upper_R" position={[0.001, 0.018, -0.022]} rotation={[-1.516, 0, 0]}>
                    <group name="Arm_Piston_Upper_R" position={[0, 0.046, 0.001]} rotation={[1.605, 0, 0]}>
                      <mesh name="Object037" geometry={nodes.Object037.geometry} material={materials.Solid_Light_Grey} rotation={[-0.089, 0, -1.571]} />
                    </group>
                    <group name="Arm_Upper_R001" position={[0, 0.036, 0]} rotation={[1.602, 0, 0]}>
                      <group name="Arm_Piston_Lower_R" position={[0, 0.057, -0.01]} rotation={[-3.137, 0.002, 0.002]}>
                        <mesh name="Object036" geometry={nodes.Object036.geometry} material={materials['Pohatu Rock']} rotation={[3.051, 0.002, -1.569]} />
                      </group>
                      <group name="Hand_R" position={[0, 0.101, 0]} rotation={[-0.086, 0, 0]}>
                        <mesh name="Object012" geometry={nodes.Object012.geometry} material={materials.Solid_Black} position={[0, 0, -0.001]} rotation={[0, 0, -Math.PI / 2]}>
                          <mesh name="Object013" geometry={nodes.Object013.geometry} material={materials.Solid_Black} position={[-0.042, 0.003, 0.021]} />
                          <mesh name="Object014" geometry={nodes.Object014.geometry} material={materials.Solid_Black} position={[-0.042, 0.003, -0.022]} />
                        </mesh>
                      </group>
                      <group name="Object034" position={[0, 0.049, -0.014]} rotation={[-0.086, 0, -Math.PI / 2]}>
                        <mesh name="Part-evanetic__kit2-8_dot_1_dot_dat001" geometry={nodes['Part-evanetic__kit2-8_dot_1_dot_dat001'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                        <mesh name="Part-evanetic__kit2-8_dot_1_dot_dat001_1" geometry={nodes['Part-evanetic__kit2-8_dot_1_dot_dat001_1'].geometry} material={materials.Solid_Light_Grey} />
                        <mesh name="Part-evanetic__kit2-8_dot_1_dot_dat001_2" geometry={nodes['Part-evanetic__kit2-8_dot_1_dot_dat001_2'].geometry} material={materials['Pohatu Rock']} />
                      </group>
                    </group>
                    <mesh name="Object035" geometry={nodes.Object035.geometry} material={materials['Pohatu_SOLID-TAN']} position={[0, 0.019, -0.014]} rotation={[1.516, 0, -Math.PI / 2]} />
                  </group>
                  <mesh name="Object041" geometry={nodes.Object041.geometry} material={materials.Solid_Black} position={[-0.01, 0.017, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object042" geometry={nodes.Object042.geometry} material={materials.Solid_Black} position={[-0.021, 0.011, 0]} />
                    <mesh name="Object043" geometry={nodes.Object043.geometry} material={materials.Solid_Black} position={[-0.032, 0.011, 0]} />
                  </mesh>
                </group>
                <group name="Body_Piston_Upper_R" position={[-0.017, 0.005, 0]} rotation={[1.565, 1.309, 1.577]}>
                  <mesh name="Object011" geometry={nodes.Object011.geometry} material={materials['Pohatu Rock']} position={[0.003, 0.011, 0]} rotation={[-0.001, 1.569, -2.879]} />
                </group>
                <group name="Head" position={[0, 0.014, 0.043]}>
                  <mesh name="Head_1" geometry={nodes.Head_1.geometry} material={materials.Solid_Light_Grey} position={[0, -0.014, 0.031]}>
                    <group name="Masks" position={[0.001, 0.046, 0.019]} scale={1.221}>
                      <mesh name="Akaku" geometry={nodes.Akaku.geometry} material={materials['Pohatu Rock']} position={[-0.003, -0.032, 0.001]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={-0.001} />
                      <mesh name="Hau" geometry={nodes.Hau.geometry} material={materials['Pohatu Rock']} position={[0, -0.034, -0.003]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Huna" geometry={nodes.Huna.geometry} material={materials['Pohatu Rock']} position={[0, -0.044, -0.007]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Kakama" geometry={nodes.Kakama.geometry} material={materials['Pohatu Rock']} position={[0, -0.031, -0.005]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Kaukau" geometry={nodes.Kaukau.geometry} material={materials['Pohatu Rock']} position={[0, -0.042, -0.005]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Komau" geometry={nodes.Komau.geometry} material={materials['Pohatu Rock']} position={[0, -0.034, -0.01]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Mahiki" geometry={nodes.Mahiki.geometry} material={materials['Pohatu Rock']} position={[0, -0.036, -0.009]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Matatu" geometry={nodes.Matatu.geometry} material={materials['Pohatu Rock']} position={[0, -0.037, -0.003]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Miru" geometry={nodes.Miru.geometry} material={materials['Pohatu Rock']} position={[0, -0.036, -0.002]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Pakari" geometry={nodes.Pakari.geometry} material={materials['Pohatu Rock']} position={[0, -0.048, -0.008]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Rau" geometry={nodes.Rau.geometry} material={materials['Pohatu Rock']} position={[0, -0.044, -0.012]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                      <mesh name="Ruru" geometry={nodes.Ruru.geometry} material={materials['Pohatu Rock']} position={[0, -0.035, -0.007]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.001} />
                    </group>
                    <mesh name="Glowing_Eyes" geometry={nodes.Glowing_Eyes.geometry} material={materials['Pohatu Eyes']} position={[0, 0.054, 0.005]} />
                    <mesh name="Object004" geometry={nodes.Object004.geometry} material={materials['Trans Neon Orange']} position={[0, 0.034, -0.015]} />
                    <mesh name="Object005" geometry={nodes.Object005.geometry} material={materials.Solid_Black} position={[0, 0.035, -0.031]} />
                  </mesh>
                </group>
                <mesh name="Chest_1" geometry={nodes.Chest_1.geometry} material={materials['Pohatu Rock']} position={[0, 0.058, 0]}>
                  <mesh name="Object001" geometry={nodes.Object001.geometry} material={materials.Solid_Black} position={[0, -0.111, 0]} />
                  <mesh name="Object002" geometry={nodes.Object002.geometry} material={materials.Solid_Black} position={[-0.001, -0.035, 0.022]} />
                  <mesh name="Object003" geometry={nodes.Object003.geometry} material={materials.Solid_Black} position={[0, -0.043, 0]} />
                </mesh>
              </group>
              <mesh name="Body_1" geometry={nodes.Body_1.geometry} material={materials['Pohatu Rock']} position={[0, 0.025, 0]} rotation={[-0.002, 0, 0]} />
            </group>
            <group name="Body_Piston_Lower_L" position={[0.029, 0.047, 0]} rotation={[-1.562, 1.31, 1.563]}>
              <mesh name="Object016" geometry={nodes.Object016.geometry} material={materials.Solid_Light_Grey} position={[0.001, 0.013, 0]} rotation={[-0.003, -1.569, -0.264]} />
            </group>
            <group name="Hip_R" position={[-0.067, 0, 0]} rotation={[3.129, -0.002, 0.002]}>
              <group name="Upper_Leg_R" position={[0, 0.043, 0]} rotation={[-0.152, 0.001, -0.001]}>
                <group name="Lower_Leg_R" position={[0, 0.063, 0]} rotation={[0.273, 0.001, -0.002]}>
                  <group name="Leg_Piston_Lower_R" position={[0, 0.057, 0.03]} rotation={[-2.793, -1.567, 0.263]}>
                    <mesh name="Object018" geometry={nodes.Object018.geometry} material={materials['Pohatu Rock']} rotation={[-1.554, 1.377, 1.554]} />
                  </group>
                  <group name="Object019" position={[0, 0.084, 0]} rotation={[3.034, 0.001, -0.001]}>
                    <mesh name="Part-Evanetic__kit2-3_dot_1_dot_dat001" geometry={nodes['Part-Evanetic__kit2-3_dot_1_dot_dat001'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                    <mesh name="Part-Evanetic__kit2-3_dot_1_dot_dat001_1" geometry={nodes['Part-Evanetic__kit2-3_dot_1_dot_dat001_1'].geometry} material={materials['Pohatu Rock']} />
                    <mesh name="Part-Evanetic__kit2-3_dot_1_dot_dat001_2" geometry={nodes['Part-Evanetic__kit2-3_dot_1_dot_dat001_2'].geometry} material={materials.Solid_Light_Grey} />
                    <mesh name="Object020" geometry={nodes.Object020.geometry} material={materials.Solid_Black} position={[-0.011, 0.043, 0]} />
                    <mesh name="Object021" geometry={nodes.Object021.geometry} material={materials.Solid_Black} position={[-0.011, 0.065, 0]} />
                  </group>
                </group>
                <group name="Leg_Piston_Upper_R" position={[0, 0.053, 0.023]} rotation={[0.36, -1.57, 0]}>
                  <mesh name="Object017" geometry={nodes.Object017.geometry} material={materials.Solid_Light_Grey} rotation={[1.566, -1.377, -1.576]} />
                </group>
                <mesh name="Object022" geometry={nodes.Object022.geometry} material={materials.Solid_Black} position={[0, 0.063, 0]} rotation={[-2.976, -0.001, 0.001]} />
                <group name="Object028" rotation={[-2.976, -0.001, 0.001]}>
                  <mesh name="Part-Evanetic__kit2-4_dot_1_dot_dat001" geometry={nodes['Part-Evanetic__kit2-4_dot_1_dot_dat001'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                  <mesh name="Part-Evanetic__kit2-4_dot_1_dot_dat001_1" geometry={nodes['Part-Evanetic__kit2-4_dot_1_dot_dat001_1'].geometry} material={materials['Pohatu Rock']} />
                  <mesh name="Part-Evanetic__kit2-4_dot_1_dot_dat001_2" geometry={nodes['Part-Evanetic__kit2-4_dot_1_dot_dat001_2'].geometry} material={materials.Solid_Light_Grey} />
                </group>
              </group>
              <mesh name="Object006" geometry={nodes.Object006.geometry} material={materials.Solid_Black} position={[-0.01, 0.024, 0]} rotation={[-3.128, -0.002, 0.002]} />
            </group>
            <group name="Body_Piston_Lower_R" position={[-0.029, 0.047, 0]} rotation={[-1.564, -1.309, -1.565]}>
              <mesh name="Object015" geometry={nodes.Object015.geometry} material={materials.Solid_Light_Grey} position={[-0.001, 0.013, 0]} rotation={[0, 1.569, 0.262]} />
            </group>
            <group name="Hip_L" position={[0.067, 0, 0]} rotation={[3.129, 0.002, -0.002]}>
              <group name="Upper_Leg_L" position={[0, 0.043, 0]} rotation={[-0.152, -0.001, 0.001]}>
                <group name="Lower_Leg_L" position={[0, 0.063, 0]} rotation={[0.273, -0.001, 0.002]}>
                  <group name="Leg_Piston_Lower_L" position={[0, 0.057, 0.03]} rotation={[-2.793, 1.567, -0.263]}>
                    <mesh name="Object030" geometry={nodes.Object030.geometry} material={materials['Pohatu Rock']} position={[-0.004, 0.016, -0.001]} rotation={[-1.554, -1.377, -1.554]} />
                  </group>
                  <group name="Object031" position={[-0.001, 0.084, 0]} rotation={[3.034, -0.001, 0.001]}>
                    <mesh name="Part-Evanetic__kit2-3_dot_1_dot_dat001" geometry={nodes['Part-Evanetic__kit2-3_dot_1_dot_dat001'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                    <mesh name="Part-Evanetic__kit2-3_dot_1_dot_dat001_1" geometry={nodes['Part-Evanetic__kit2-3_dot_1_dot_dat001_1'].geometry} material={materials['Pohatu Rock']} />
                    <mesh name="Part-Evanetic__kit2-3_dot_1_dot_dat001_2" geometry={nodes['Part-Evanetic__kit2-3_dot_1_dot_dat001_2'].geometry} material={materials.Solid_Light_Grey} />
                    <mesh name="Object032" geometry={nodes.Object032.geometry} material={materials.Solid_Black} position={[0.011, 0.043, 0]} />
                    <mesh name="Object033" geometry={nodes.Object033.geometry} material={materials.Solid_Black} position={[0.011, 0.065, 0]} />
                  </group>
                </group>
                <group name="Leg_Piston_Upper_L" position={[0, 0.053, 0.023]} rotation={[0.36, 1.57, 0]}>
                  <mesh name="Object029" geometry={nodes.Object029.geometry} material={materials.Solid_Light_Grey} position={[0.002, 0.017, -0.001]} rotation={[1.566, 1.377, 1.576]} />
                </group>
                <group name="Object048" position={[-0.001, 0, 0]} rotation={[-2.976, 0.001, -0.001]}>
                  <mesh name="Part-Evanetic__kit2-4_dot_1_dot_dat002" geometry={nodes['Part-Evanetic__kit2-4_dot_1_dot_dat002'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                  <mesh name="Part-Evanetic__kit2-4_dot_1_dot_dat002_1" geometry={nodes['Part-Evanetic__kit2-4_dot_1_dot_dat002_1'].geometry} material={materials['Pohatu Rock']} />
                  <mesh name="Part-Evanetic__kit2-4_dot_1_dot_dat002_2" geometry={nodes['Part-Evanetic__kit2-4_dot_1_dot_dat002_2'].geometry} material={materials['Pohatu Rock']} />
                  <mesh name="Object049" geometry={nodes.Object049.geometry} material={materials.Solid_Black} position={[0, -0.063, 0.01]} />
                </group>
              </group>
              <mesh name="Object027" geometry={nodes.Object027.geometry} material={materials.Solid_Black} position={[-0.01, 0.024, 0]} rotation={[-3.128, 0.002, -0.002]} />
            </group>
            <mesh name="Waist_1" geometry={nodes.Waist_1.geometry} material={materials['Pohatu Rock']} position={[0, 0.068, -0.011]} rotation={[0.001, 0, 0]}>
              <mesh name="Object050" geometry={nodes.Object050.geometry} material={materials.Solid_Black} position={[0.022, -0.046, 0.011]} />
              <mesh name="Object051" geometry={nodes.Object051.geometry} material={materials.Solid_Light_Grey} position={[0, -0.067, 0.033]} />
              <mesh name="Object052" geometry={nodes.Object052.geometry} material={materials.Solid_Black} position={[0, -0.067, -0.021]} />
              <mesh name="Object053" geometry={nodes.Object053.geometry} material={materials.Solid_Light_Grey} position={[0, -0.067, -0.075]} />
              <mesh name="Object054" geometry={nodes.Object054.geometry} material={materials.Solid_Light_Grey} position={[0, -0.067, -0.011]} />
              <mesh name="Object055" geometry={nodes.Object055.geometry} material={materials.Solid_Light_Grey} position={[-0.021, -0.067, 0.011]} />
              <mesh name="Object056" geometry={nodes.Object056.geometry} material={materials.Solid_Black} position={[0, -0.035, 0.011]} />
              <mesh name="Object057" geometry={nodes.Object057.geometry} material={materials.Solid_Black} position={[0, -0.068, 0.011]} />
              <mesh name="Object058" geometry={nodes.Object058.geometry} material={materials.Solid_Light_Grey} position={[0, -0.067, -0.054]} />
              <mesh name="Object059" geometry={nodes.Object059.geometry} material={materials.Solid_Black} position={[-0.043, -0.076, 0.011]} />
              <mesh name="Object060" geometry={nodes.Object060.geometry} material={materials.Solid_Black} position={[0.043, -0.076, 0.011]} />
            </mesh>
          </group>
          <group name="LegIKTargetL" position={[0.067, -0.189, 0.002]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Foot_L" rotation={[-2.976, -0.001, 0]}>
              <group name="Object023" position={[-0.001, 0, 0]} rotation={[-1.736, 0, 0.001]}>
                <mesh name="Part-32475_dot_dat001" geometry={nodes['Part-32475_dot_dat001'].geometry} material={materials['Pohatu Rock']} />
                <mesh name="Part-32475_dot_dat001_1" geometry={nodes['Part-32475_dot_dat001_1'].geometry} material={materials.Solid_Light_Grey} />
                <group name="Object024" position={[0, -0.02, 0.132]}>
                  <mesh name="Part-32560_dot_dat003" geometry={nodes['Part-32560_dot_dat003'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                  <mesh name="Part-32560_dot_dat003_1" geometry={nodes['Part-32560_dot_dat003_1'].geometry} material={materials.Solid_Light_Grey} />
                </group>
              </group>
            </group>
            <group name="LegIKPoleL" position={[0, -0.164, 0.083]} rotation={[-Math.PI, 0.002, 0]} />
          </group>
          <group name="LegIKTargetR" position={[-0.067, -0.189, 0.002]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Foot_R" rotation={[-2.976, 0.001, 0]}>
              <group name="Object025" rotation={[-1.736, 0, -0.001]}>
                <mesh name="Part-32475_dot_dat001" geometry={nodes['Part-32475_dot_dat001'].geometry} material={materials['Pohatu Rock']} />
                <mesh name="Part-32475_dot_dat001_1" geometry={nodes['Part-32475_dot_dat001_1'].geometry} material={materials.Solid_Light_Grey} />
                <group name="Object026" position={[0, -0.02, 0.132]}>
                  <mesh name="Part-32560_dot_dat004" geometry={nodes['Part-32560_dot_dat004'].geometry} material={materials['Pohatu_SOLID-TAN']} />
                  <mesh name="Part-32560_dot_dat004_1" geometry={nodes['Part-32560_dot_dat004_1'].geometry} material={materials.Solid_Light_Grey} />
                </group>
              </group>
            </group>
            <group name="LegIKPoleR" position={[0, -0.164, 0.083]} rotation={[Math.PI, -0.002, 0]} />
          </group>
        </group>
        <mesh name="Rock" geometry={nodes.Rock.geometry} material={materials['Pohatu Rock']} position={[-0.938, 0.079, 0.044]} />
      </group>
    </group>
  )
}

useGLTF.preload('/toa_pohatu_mata-transformed.glb')
