import { VitePWA } from 'vite-plugin-pwa';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { watch } from 'vite-plugin-watch';

// https://vitejs.dev/config/
export default defineConfig({
  base: '/BionicleIdleRPG/',
  plugins: [
    react(),
    VitePWA({
      injectRegister: false,

      pwaAssets: {
        disabled: true,
      },

      manifest: {
        name: 'BionicleIdleRpg',
        short_name: 'Bionicle',
        description: 'BionicleIdleRpg',
        theme_color: '#ffffff',
        background_color: '#ffffff',
        icons: [
          // Light mode raster icons (generated by pwa-asset-generator)
          {
            src: 'pwa-icons/light/manifest-icon-192.maskable.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'pwa-icons/light/manifest-icon-512.maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'pwa-icons/light/manifest-icon-512.maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
          // Monochrome icon for adaptive/tinted rendering and liquid glass (iOS 26+)
          {
            src: 'ThreeVirtues-monochrome.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'monochrome',
          },
        ],
      },

      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,glb}'],
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        maximumFileSizeToCacheInBytes: 10485760,
      },

      devOptions: {
        enabled: false,
        navigateFallback: 'index.html',
        suppressWarnings: true,
        type: 'module',
      },
    }),
    watch({
      pattern: 'src/data/quests/**/*',
      command: 'tsx tools/generate-quest-graph.ts',
    }),
  ],
  build: {
    rollupOptions: {
      external: ['tools'],
    },
  },
});
