import { VitePWA } from 'vite-plugin-pwa';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { watch } from 'vite-plugin-watch';

// Extended icon type supporting newer manifest spec fields (color_scheme, design)
// not yet in vite-plugin-pwa's types
interface ExtendedIconResource {
  src: string;
  sizes?: string;
  type?: string;
  purpose?: string;
  /** W3C color_scheme for dark/light mode icon variants */
  color_scheme?: 'light' | 'dark';
  /** Apple liquid glass design for iOS 26+ / macOS Tahoe */
  design?: 'liquid-glass';
}

// https://vitejs.dev/config/
export default defineConfig({
  base: '/BionicleIdleRPG/',
  plugins: [
    react(),
    VitePWA({
      injectRegister: false,

      pwaAssets: {
        disabled: true,
      },

      manifest: {
        name: 'BionicleIdleRpg',
        short_name: 'Bionicle',
        description: 'BionicleIdleRpg',
        theme_color: '#ffffff',
        background_color: '#ffffff',
        icons: ([
          // Adaptive SVG icon — auto-switches dark/light via prefers-color-scheme CSS
          // Browsers that support SVG manifest icons will use this as the
          // primary icon and it auto-adapts to the system color scheme.
          {
            src: 'favicon.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any',
          },
          // Light mode SVG icon (explicit color_scheme for browsers that support it)
          {
            src: 'ThreeVirtues-light.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any',
            color_scheme: 'light',
          },
          // Dark mode SVG icon (explicit color_scheme for browsers that support it)
          {
            src: 'ThreeVirtues-dark.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any',
            color_scheme: 'dark',
          },
          // Light mode raster icons (generated by pwa-asset-generator)
          {
            src: 'pwa-icons/light/manifest-icon-192.maskable.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'pwa-icons/light/manifest-icon-512.maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          // Maskable icons for safe-zone cropping
          {
            src: 'pwa-icons/light/manifest-icon-512.maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
          // Monochrome icon for adaptive/tinted icon rendering
          {
            src: 'ThreeVirtues-monochrome.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'monochrome',
          },
          // Liquid glass icon for iOS 26+ / macOS Tahoe
          // The system applies the translucent glass effect over the glyph
          {
            src: 'ThreeVirtues-monochrome.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any',
            design: 'liquid-glass',
          },
        ] satisfies ExtendedIconResource[]) as typeof undefined,
        // Extended manifest fields for dark mode theming (Chrome 132+)
        ...({
          dark_theme_color: '#2d2d2d',
          dark_background_color: '#2d2d2d',
        } as Record<string, string>),
      },

      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,glb}'],
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        maximumFileSizeToCacheInBytes: 10485760,
      },

      devOptions: {
        enabled: false,
        navigateFallback: 'index.html',
        suppressWarnings: true,
        type: 'module',
      },
    }),
    watch({
      pattern: 'src/data/quests/**/*',
      command: 'tsx tools/generate-quest-graph.ts',
    }),
  ],
  build: {
    rollupOptions: {
      external: ['tools'],
    },
  },
});
