import { VitePWA, type IconResource } from 'vite-plugin-pwa';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import { watch } from 'vite-plugin-watch';
import { readFileSync } from 'fs';
import { execSync } from 'child_process';

const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));

let commitHash = 'unknown';
try {
  commitHash = execSync('git rev-parse --short HEAD').toString().trim();
} catch {
  console.warn('Failed to get git commit hash, using "unknown"');
}
const appVersion = `${pkg.version}+${commitHash}`;

// Extended icon type supporting newer manifest spec fields (color_scheme, design)
// not yet in vite-plugin-pwa's types
interface ExtendedIconResource {
  src: string;
  sizes?: string;
  type?: string;
  purpose?: string;
  /** W3C color_scheme for dark/light mode icon variants */
  color_scheme?: 'light' | 'dark';
  /** Apple liquid glass design for iOS 26+ / macOS Tahoe */
  design?: 'liquid-glass';
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), 'VITE_');

  return {
    base: '/BionicleIdleRPG/',
    plugins: [
      react(),
      VitePWA({
        injectRegister: false,

        pwaAssets: {
          disabled: false,
          config: true,
          // Favicon / theme-color are declared in index.html (base path + adaptive SVG).
          includeHtmlHeadLinks: false,
          injectThemeColor: false,
        },

        manifest: {
          name: 'BionicleIdleRpg',
          short_name: 'Bionicle',
          description: 'BionicleIdleRpg',
          theme_color: '#ffffff',
          background_color: '#ffffff',
          icons: [
            // Raster icons (generated by pwa-assets from ThreeVirtues-light.svg; transparent background)
            { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
            { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
            {
              src: 'maskable-icon-512x512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'maskable',
            },
            // Default SVG (silver glyph, transparent; tab favicon also uses prefers-color-scheme in the SVG)
            {
              src: 'ThreeVirtues-default.svg',
              sizes: 'any',
              type: 'image/svg+xml',
              purpose: 'any',
            },
            {
              src: 'ThreeVirtues-light.svg',
              sizes: 'any',
              type: 'image/svg+xml',
              purpose: 'any',
              color_scheme: 'light',
            },
            {
              src: 'ThreeVirtues-dark.svg',
              sizes: 'any',
              type: 'image/svg+xml',
              purpose: 'any',
              color_scheme: 'dark',
            },
            // Monochrome icon for adaptive/tinted icon rendering
            {
              src: 'ThreeVirtues-monochrome.svg',
              sizes: 'any',
              type: 'image/svg+xml',
              purpose: 'monochrome',
            },
            // Liquid glass icon for iOS 26+ / macOS Tahoe
            // The system applies the translucent glass effect over the glyph
            {
              src: 'ThreeVirtues-monochrome.svg',
              sizes: 'any',
              type: 'image/svg+xml',
              purpose: 'any',
              design: 'liquid-glass',
            },
          ] satisfies ExtendedIconResource[] as unknown as IconResource[],
          // Extended manifest fields for dark mode theming
          ...({ dark_theme_color: '#2d2d2d', dark_background_color: '#2d2d2d' } as Record<
            string,
            string
          >),
        },

        strategies: 'injectManifest',
        srcDir: 'src',
        filename: 'sw.ts',
        injectManifest: {
          globPatterns: ['**/*.{js,css,html,svg,png,ico,glb,woff2,ttf}'],
          maximumFileSizeToCacheInBytes: 10485760,
        },

        devOptions: {
          enabled: false,
          navigateFallback: 'index.html',
          suppressWarnings: true,
          type: 'module',
        },
      }),
      watch({
        pattern: 'src/data/quests/**/*',
        command: 'tsx tools/generate-quest-graph.ts',
      }),
    ],
    define: {
      __APP_VERSION__: JSON.stringify(appVersion),
      __TELEMETRY_URL__: JSON.stringify(env.VITE_TELEMETRY_URL ?? ''),
    },
    build: {
      rollupOptions: {
        external: ['tools'],
      },
    },
  };
});
