import { KIT_2001_NODES } from './kit2001Nodes';

/**
 * Material slot names on each attachable node in the kit GLB.
 * Keys match `KIT_2001_NODES`; values are `materialColors` config keys.
 * Regenerate: `yarn kit-material-slots-report --write`
 */
export const KIT_2001_MATERIAL_SLOTS = {
  Axle2L: ['Main'] as const,
  Axle3L: ['Main'] as const,
  Axle6L: ['Main'] as const,
  AxleConnRidged: ['Main'] as const,
  AxleConPin1: ['Main'] as const,
  AxleConPin2: ['Main'] as const,
  AxleMod2L: ['Main'] as const,
  AxleMod3L: ['Main'] as const,
  AxleModHips: ['Main'] as const,
  AxlePin: ['Main'] as const,
  AxlePinPerp3L: ['Main'] as const,
  AxleSocket1L: ['Main'] as const,
  AxleSocket3L: ['Main'] as const,
  AxleSpacer1L: ['Main'] as const,
  BallJoint: ['Main'] as const,
  Claw: ['Main', 'Metal'] as const,
  FootKick: ['Main', 'Metal', 'Secondary'] as const,
  GearB: ['Main'] as const,
  GearM: ['Main'] as const,
  Hook: ['Glow', 'Main', 'Metal'] as const,
  KopakaShield: ['Kopaka Tool'] as const,
  KopakaSword: ['Glow', 'Main', 'Metal'] as const,
  LewaAxe: ['Glow', 'Main', 'Metal'] as const,
  MataAbdomen: ['Main'] as const,
  MataBrain: ['Brain'] as const,
  MataChest: ['Main'] as const,
  MataFace: ['Face'] as const,
  MataFoot: ['Main', 'Metal', 'Secondary'] as const,
  MataGlowingEyes: ['Glowing Eyes'] as const,
  MataHand: ['Main'] as const,
  MataHip: ['Main'] as const,
  MataLegModPistonN: ['Metal'] as const,
  MataLegModPistonT: ['Main'] as const,
  MataLegModShin: ['Main', 'Metal', 'Secondary', 'Solid_Black'] as const,
  MataLegModThigh: ['Main', 'Metal', 'Secondary'] as const,
  MataObliqueN: ['Metal'] as const,
  MataObliqueW: ['Main'] as const,
  MataSingleArmHand: ['Main', 'Secondary'] as const,
  MataSingleArmLower: ['Main', 'Secondary'] as const,
  MataSingleArmPistonLowerL: ['Main'] as const,
  MataSingleArmPistonUpperL: ['Metal'] as const,
  MataSingleArmUpper: ['Main', 'Metal', 'Secondary', 'Solid_Black'] as const,
  MatoranFoot: ['Main'] as const,
  McArmL: ['Main'] as const,
  McArmR: ['Main'] as const,
  McToranFace: ['Brain', 'Face', 'Glowing Eyes'] as const,
  McTorso: ['Main'] as const,
  PerpendicularAxleJoint: ['Main'] as const,
  Pin2L: ['Main'] as const,
  Socket: ['Main'] as const,
  SocketModSide: ['Main'] as const,
  SocketModTop: ['Main'] as const,
  TahuSword: ['Glow', 'Main', 'Metal', 'Secondary'] as const,
  TechnicArmJoint: ['Main', 'Secondary'] as const,
  TechnicArmMain: ['Main', 'Metal', 'Secondary'] as const,
  TechnicArmPistonN: ['Metal'] as const,
  TechnicArmPistonT: ['Main'] as const,
} as const satisfies Record<keyof typeof KIT_2001_NODES, readonly string[]>;

export type Kit2001MaterialSlotMap = typeof KIT_2001_MATERIAL_SLOTS;
