/**
 * Tahu kit socket keys → `lewa.glb` bone names (Three.js `nodes` keys / sanitized glTF names).
 * Lewa’s rig uses different labels than Tahu; this aligns attachment lookup without editing the GLB.
 */
export const LEWA_MATA_KIT_SOCKET_ALIASES: Record<string, string> = {
  Ankle_L: 'Leg_Lower_L001',
  Ankle_R: 'Leg_Lower_R',
  Arm_L_Piston_Lower_1: 'Arm_Piston_Lower_L',
  Arm_L_Piston_Upper_1: 'Arm_Piston_Upper_L',
  Arm_Lower_L_1: 'Arm_Upper_L002',
  Arm_Lower_R_1: 'Arm_Lower_R',
  Arm_R_Piston_Lower_L_1: 'Arm_R_Piston_Lower_1',
  Arm_R_Piston_Lower_R_1: 'Arm_R_Piston_Lower_2',
  Arm_R_Piston_Upper_L_1: 'Arm_R_Piston_Upper_1',
  Arm_R_Piston_Upper_R_1: 'Arm_R_Piston_Upper_2',
  Arm_Upper_L_1: 'Arm_Upper_L001',
  Arm_Upper_R_1: 'Arm_Upper_R',
  ArmJointStopper: 'Waist_2',
  Axle6L: 'Waist_2',
  AxleMod2L: 'Neck',
  AxleModHips: 'Body',
  AxleSocket1L: 'Head_1',
  BallJoint: 'Waist_2',
  Brain: 'Head_1',
  Chest: 'Waist_2',
  Face: 'Head_1',
  FingerB: 'Lewa_Hand_L',
  FingerF: 'Lewa_Hand_L',
  Foot_L_1: 'Foot_L',
  Foot_R_1: 'Foot_R',
  GearB: 'Waist_2',
  GearMM: 'Waist_2',
  GearMR: 'Shoulder_R',
  HandL: 'Lewa_Hand_L',
  HandR: 'Hand_R',
  Hip_Joint_L_1: 'Hip_Joint_L',
  Hip_Joint_R_1: 'Hip_Joint_R',
  Leg_Lower_Piston_L_1: 'Leg_Lower_Piston_L',
  Leg_Lower_Piston_R_1: 'Leg_Lower_Piston_R',
  Leg_Upper_L_1: 'Leg_Upper_L',
  Leg_Upper_Piston_L_1: 'Leg_Upper_Piston_L',
  Leg_Upper_Piston_R_1: 'Leg_Upper_Piston_R',
  Leg_Upper_R_1: 'Leg_Upper_R',
  MataHip: 'Body',
  Neck_1: 'Neck',
  Shoulder_Joint_L_1: 'Shoulder_Joint_L',
  Shoulder_Joint_R_1: 'Shoulder_Joint_R',
  Shoulder_L_1: 'Shoulder_L',
  Shoulder_R_1: 'Shoulder_R',
  Spacer1LB: 'Waist_2',
  Spacer1LF: 'Waist_2',
  Waist_1_1: 'Waist_1',
  Waist_Piston_Lower_L_1: 'Waist_Piston_Lower_L',
  Waist_Piston_Lower_R_1: 'Waist_Piston_Lower_R',
  Waist_Piston_Upper_L_1: 'Waist_Piston_Upper_L',
  Waist_Piston_Upper_R_1: 'Waist_Piston_Upper_R',
};
