/**
 * Tahu kit socket keys → `pohatu.glb` bone names (Three.js `nodes` keys).
 */
export const POHATU_MATA_KIT_SOCKET_ALIASES: Record<string, string> = {
  Ankle_L: 'Lower_Leg_L',
  Ankle_R: 'Lower_Leg_R',
  Arm_L_Piston_Lower_1: 'Arm_Piston_Lower_L',
  Arm_L_Piston_Upper_1: 'Arm_Piston_Upper_L',
  Arm_Lower_L_1: 'Arm_Lower_L',
  Arm_Lower_R_1: 'Arm_Upper_R002',
  Arm_R_Piston_Lower_L_1: 'Arm_Piston_Lower_R',
  Arm_R_Piston_Lower_R_1: 'Arm_Piston_Lower_R',
  Arm_R_Piston_Upper_L_1: 'Arm_Piston_Upper_R',
  Arm_R_Piston_Upper_R_1: 'Arm_Piston_Upper_R',
  Arm_Upper_L_1: 'Arm_Upper_L',
  Arm_Upper_R_1: 'Arm_Upper_R',
  ArmJointStopper: 'Chest',
  Axle6L: 'Chest',
  AxleMod2L: 'Head_1',
  AxleModHips: 'Body_1',
  AxleSocket1L: 'Head_1',
  BallJoint: 'Chest',
  Brain: 'Head_1',
  Chest: 'Chest',
  Face: 'Head_1',
  FingerB: 'Hand_L',
  FingerF: 'Hand_L',
  Foot_L_1: 'Foot_L',
  Foot_R_1: 'Foot_R',
  GearB: 'Chest',
  GearMM: 'Chest',
  GearMR: 'Shoulder_R',
  HandL: 'Hand_L',
  HandR: 'Hand_R',
  Hip_Joint_L_1: 'Hip_L',
  Hip_Joint_R_1: 'Hip_R',
  Leg_Lower_Piston_L_1: 'Leg_Piston_Lower_L',
  Leg_Lower_Piston_R_1: 'Leg_Piston_Lower_R',
  Leg_Upper_L_1: 'Upper_Leg_L',
  Leg_Upper_Piston_L_1: 'Leg_Piston_Upper_L',
  Leg_Upper_Piston_R_1: 'Leg_Piston_Upper_R',
  Leg_Upper_R_1: 'Upper_Leg_R',
  MataHip: 'Body_1',
  Neck_1: 'Head',
  Shoulder_Joint_L_1: 'Shoulder_L',
  Shoulder_Joint_R_1: 'Shoulder_R',
  Shoulder_L_1: 'Shoulder_L',
  Shoulder_R_1: 'Shoulder_R',
  Spacer1LB: 'Chest',
  Spacer1LF: 'Chest',
  Waist_1_1: 'Waist_1',
  Waist_Piston_Lower_L_1: 'Body_Piston_Lower_L',
  Waist_Piston_Lower_R_1: 'Body_Piston_Lower_R',
  Waist_Piston_Upper_L_1: 'Body_Piston_Upper_L',
  Waist_Piston_Upper_R_1: 'Body_Piston_Upper_R',
};
