import { readFileSync } from 'node:fs';
import {
  ANIMATION_EPICS,
  type AnimationEpicId,
  type ClipBacklog,
  type ExpectedClip,
  findRigByGlb,
  getUnexpectedShippedClips,
  isRigAnimationComplete,
  type RigInventoryEntry,
  RIG_INVENTORY,
  sortEpicIdsByStory,
  STORY_ARC_LABELS,
} from '../src/rendering/3d/CharacterScene/characterAnimationInventory';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
export const PUBLIC_DIR = join(repoRoot, 'public');

const GLB_HEADER_BYTES = 12;
const CHUNK_HEADER_BYTES = 8;

/** Reads clip names out of a GLB JSON chunk (scripts copy — avoids importing Jest-only glbClipUtils). */
function readGlbClipNames(relativePath: string, publicDir: string = PUBLIC_DIR): string[] {
  const buffer = readFileSync(join(publicDir, relativePath));
  const jsonChunkLength = buffer.readUInt32LE(GLB_HEADER_BYTES);
  const jsonStart = GLB_HEADER_BYTES + CHUNK_HEADER_BYTES;
  const gltf = JSON.parse(buffer.subarray(jsonStart, jsonStart + jsonChunkLength).toString());
  return (gltf.animations ?? []).map((animation: { name: string }) => animation.name);
}

export type ClipPresence = 'shipped' | 'procedural' | 'na';

export interface ClipReportRow {
  clip: ExpectedClip;
  presence: ClipPresence;
  status: ClipBacklog;
}

export interface RigReportRow {
  rig: RigInventoryEntry;
  clips: ClipReportRow[];
  shippedClipNames: string[];
}

function resolveClipStatus(clip: ExpectedClip, shipped: boolean): ClipBacklog {
  if (clip.backlog === 'unused' || clip.backlog === 'revision') {
    return clip.backlog;
  }
  if (shipped) {
    return 'complete';
  }
  if (clip.kind === 'combat' && clip.required) {
    return 'missing';
  }
  if (clip.required) {
    return 'missing';
  }
  return clip.backlog ?? 'missing';
}

function resolvePresence(
  clip: ExpectedClip,
  shipped: boolean,
  role: RigInventoryEntry['role']
): ClipPresence {
  if (shipped) return 'shipped';
  if (clip.kind === 'combat' && role !== 'placeholder' && clip.required) {
    return 'procedural';
  }
  if (clip.kind === 'combat' && role === 'placeholder') {
    return 'procedural';
  }
  return 'na';
}

export function buildRigReports(publicDir: string = PUBLIC_DIR): RigReportRow[] {
  return RIG_INVENTORY.map((rig) => {
    const shippedClipNames = rig.glb ? readGlbClipNames(rig.glb, publicDir) : [];
    const clips = rig.expectedClips.map((clip) => {
      const shipped = shippedClipNames.includes(clip.name);
      return {
        clip,
        presence: resolvePresence(clip, shipped, rig.role),
        status: resolveClipStatus(clip, shipped),
      };
    });
    return { clips, rig, shippedClipNames };
  });
}

const STATUS_ICON: Record<ClipBacklog, string> = {
  complete: '✅',
  missing: '❌',
  revision: '🔧',
  unused: '💤',
};

function formatClipCell(row: ClipReportRow): string {
  const icon = STATUS_ICON[row.status];
  if (row.presence === 'procedural') {
    return `${icon} ${row.clip.name} _(procedural)_`;
  }
  if (row.status === 'unused') {
    return `${icon} ${row.clip.name} _(unused)_`;
  }
  if (row.status === 'complete') {
    return `${icon} ${row.clip.name}`;
  }
  return `${icon} ${row.clip.name}`;
}

export function buildMarkdownReport(publicDir: string = PUBLIC_DIR): string {
  const reports = buildRigReports(publicDir);
  const openEpicIds = sortEpicIdsByStory([
    ...new Set(
      RIG_INVENTORY.map((rig) => rig.epicId).filter(
        (id): id is AnimationEpicId => id !== 'complete'
      )
    ),
  ]);

  const lines: string[] = [
    '## Character animation inventory',
    '',
    '_Generated by `yarn animation-clip-report`. Epics are sorted by story progression (earliest game content first). Update [`characterAnimationInventory.ts`](../src/rendering/3d/CharacterScene/characterAnimationInventory.ts) when clip contracts change._',
    '',
    '### Epic backlog (story order)',
    '',
    '| # | Epic | Story arc | Open rigs | Summary |',
    '| ---: | --- | --- | ---: | --- |',
  ];

  openEpicIds.forEach((epicId, index) => {
    const epic = ANIMATION_EPICS[epicId];
    const openRigs = reports.filter((row) => row.rig.epicId === epicId);
    lines.push(
      `| ${index + 1} | **${epic.title}** | ${STORY_ARC_LABELS[epic.storyArc]} | ${openRigs.length} | ${epic.summary} |`
    );
  });

  lines.push('', '### Rig matrix', '');

  for (const epicId of ['complete', ...openEpicIds] as const) {
    const epicRows = reports.filter((row) => row.rig.epicId === epicId);
    if (epicRows.length === 0) continue;

    const heading =
      epicId === 'complete'
        ? 'Complete / reference rigs'
        : ANIMATION_EPICS[epicId as AnimationEpicId].title;
    lines.push(`#### ${heading}`, '');
    lines.push('| Rig | GLB | Idle | Attack | Hit | Defeat | Other | Notes |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- | --- |');

    for (const { clips, rig, shippedClipNames } of epicRows) {
      const byName = Object.fromEntries(clips.map((row) => [row.clip.name, row]));
      const cell = (name: string) => (byName[name] ? formatClipCell(byName[name]) : '—');

      const otherClips = clips.filter(
        (row) => !['Idle', 'Attack', 'Hit', 'Defeat', 'Empty'].includes(row.clip.name)
      );
      const other =
        otherClips.length > 0
          ? otherClips.map((row) => formatClipCell(row)).join('<br>')
          : shippedClipNames
              .filter(
                (name) =>
                  !rig.expectedClips.some((clip) => clip.name === name) &&
                  !['Idle', 'Attack', 'Hit', 'Defeat'].includes(name)
              )
              .map((name) => `💤 ${name} _(unexpected)_`)
              .join('<br>') || '—';

      const idleCell =
        byName['Idle'] != null
          ? cell('Idle')
          : byName['Empty'] != null
            ? cell('Empty')
            : rig.expectedClips
                .filter((clip) => clip.kind === 'idle-switch' || clip.kind === 'transition')
                .map((clip) => formatClipCell(byName[clip.name]))
                .join('<br>') || '—';

      lines.push(
        `| ${rig.displayName} | \`${rig.glb ?? '—'}\` | ${idleCell} | ${cell('Attack')} | ${cell('Hit')} | ${cell('Defeat')} | ${other} | ${rig.notes ?? ''} |`
      );
    }

    lines.push('');
  }

  const missingCount = reports
    .flatMap((row) => row.clips)
    .filter((clip) => clip.status === 'missing').length;
  lines.push(
    '---',
    '',
    `**Totals:** ${RIG_INVENTORY.length} tracked rigs · ${missingCount} clips marked missing · ${reports.filter((row) => row.rig.epicId === 'complete').length} reference-complete rigs`
  );

  return lines.join('\n');
}

export function countMissingClips(publicDir: string = PUBLIC_DIR): number {
  return buildRigReports(publicDir)
    .flatMap((row) => row.clips)
    .filter((clip) => clip.status === 'missing').length;
}

export interface GlbInspectResult {
  glb: string;
  rig: RigInventoryEntry | null;
  shippedClips: string[];
  report: RigReportRow | null;
  /** Required clips expected by inventory but absent from the GLB. */
  stillMissing: ExpectedClip[];
  /** Clips now in the GLB that inventory still marks missing (update backlog → complete). */
  newlyComplete: ExpectedClip[];
  /** Clips in the GLB with no inventory row (add as unused or wire in code). */
  unexpectedClips: string[];
  /** All required clips present — candidate to move rig epicId to `complete`. */
  rigComplete: boolean;
}

export function inspectGlb(glbPath: string, publicDir: string = PUBLIC_DIR): GlbInspectResult {
  const glb = glbPath
    .replace(/\\/g, '/')
    .replace(/^public\//, '')
    .replace(/^\.\//, '');
  const rig = findRigByGlb(glb) ?? null;
  const shippedClips = readGlbClipNames(glb, publicDir);
  const report = rig
    ? (buildRigReports(publicDir).find((row) => row.rig.id === rig.id) ?? null)
    : null;

  if (!rig) {
    return {
      glb,
      newlyComplete: [],
      report: null,
      rig: null,
      rigComplete: false,
      shippedClips,
      stillMissing: [],
      unexpectedClips: shippedClips,
    };
  }

  const stillMissing = rig.expectedClips.filter(
    (clip) => clip.required && !shippedClips.includes(clip.name)
  );
  const newlyComplete = rig.expectedClips.filter(
    (clip) => shippedClips.includes(clip.name) && clip.backlog === 'missing'
  );

  return {
    glb,
    newlyComplete,
    report,
    rig,
    rigComplete: isRigAnimationComplete(rig, shippedClips),
    shippedClips,
    stillMissing,
    unexpectedClips: getUnexpectedShippedClips(rig, shippedClips),
  };
}

export function buildGlbInspectMarkdown(result: GlbInspectResult): string {
  const lines: string[] = [`## GLB inspect: \`${result.glb}\``, ''];

  if (!result.rig) {
    lines.push(
      '⚠️ **Not in animation inventory.** Add a row to `characterAnimationInventory.ts` before merging.',
      '',
      '**Shipped clips:**',
      result.shippedClips.length > 0
        ? result.shippedClips.map((c) => `- \`${c}\``).join('\n')
        : '- _(none)_'
    );
    return lines.join('\n');
  }

  lines.push(
    ...[
      `**Rig:** ${result.rig.displayName} (\`${result.rig.reactComponent}\`)`,
      `**Epic:** \`${result.rig.epicId}\`${result.rig.epicId !== 'complete' ? ` — ${ANIMATION_EPICS[result.rig.epicId as AnimationEpicId]?.title ?? ''}` : ''}`,
      result.rig.epicId !== 'complete'
        ? `**Story:** ${STORY_ARC_LABELS[ANIMATION_EPICS[result.rig.epicId as AnimationEpicId].storyArc]} (\`${ANIMATION_EPICS[result.rig.epicId as AnimationEpicId].storyBeat}\`)`
        : null,
      `**Role:** ${result.rig.role}`,
      '',
      '**Shipped clips:**',
      result.shippedClips.length > 0
        ? result.shippedClips.map((c) => `- \`${c}\``).join('\n')
        : '- _(none)_',
      '',
    ].filter((line): line is string => line != null)
  );

  if (result.newlyComplete.length > 0) {
    lines.push(
      '### ✅ Newly shipped (update inventory `backlog` → `complete`)',
      '',
      ...result.newlyComplete.map(
        (clip) => `- \`${clip.name}\` (${clip.kind}) — was \`backlog: 'missing'\` in inventory`
      ),
      ''
    );
  }

  if (result.stillMissing.length > 0) {
    lines.push(
      '### ❌ Still missing from GLB',
      '',
      ...result.stillMissing.map((clip) => `- \`${clip.name}\` (${clip.kind}, required)`),
      ''
    );
  }

  if (result.unexpectedClips.length > 0) {
    lines.push(
      '### 💤 Unexpected clips (in GLB, not in inventory)',
      '',
      ...result.unexpectedClips.map(
        (name) => `- \`${name}\` — add to inventory as \`backlog: 'unused'\` or wire in code`
      ),
      ''
    );
  }

  if (result.rigComplete && result.rig.epicId !== 'complete') {
    lines.push(
      '### Epic graduation',
      '',
      `All **required** clips are present. Consider moving this rig's \`epicId\` to \`'complete'\` and updating epic rig counts in \`docs/CHARACTER_ANIMATIONS.md\`.`,
      ''
    );
  }

  if (
    result.newlyComplete.length === 0 &&
    result.stillMissing.length === 0 &&
    result.unexpectedClips.length === 0
  ) {
    lines.push('_Inventory already matches shipped clips._', '');
  }

  lines.push(
    '**Next:** edit `characterAnimationInventory.ts` → run `yarn test:ci --testPathPatterns=characterIdleClips` → `yarn animation-clip-report`'
  );

  return lines.join('\n');
}
