import {
  ANIMATION_EPICS,
  type AnimationEpicId,
  type ClipBacklog,
  type ExpectedClip,
  type RigInventoryEntry,
  RIG_INVENTORY,
} from '../src/rendering/3d/CharacterScene/characterAnimationInventory';
import { readGlbClipNames } from '../src/rendering/3d/CharacterScene/glbClipUtils';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
export const PUBLIC_DIR = join(repoRoot, 'public');

export type ClipPresence = 'shipped' | 'procedural' | 'na';

export interface ClipReportRow {
  clip: ExpectedClip;
  presence: ClipPresence;
  status: ClipBacklog;
}

export interface RigReportRow {
  rig: RigInventoryEntry;
  clips: ClipReportRow[];
  shippedClipNames: string[];
}

function resolveClipStatus(clip: ExpectedClip, shipped: boolean): ClipBacklog {
  if (clip.backlog === 'unused' || clip.backlog === 'revision') {
    return clip.backlog;
  }
  if (shipped) {
    return 'complete';
  }
  if (clip.kind === 'combat' && clip.required) {
    return 'missing';
  }
  if (clip.required) {
    return 'missing';
  }
  return clip.backlog ?? 'missing';
}

function resolvePresence(
  clip: ExpectedClip,
  shipped: boolean,
  role: RigInventoryEntry['role']
): ClipPresence {
  if (shipped) return 'shipped';
  if (clip.kind === 'combat' && role !== 'placeholder' && clip.required) {
    return 'procedural';
  }
  if (clip.kind === 'combat' && role === 'placeholder') {
    return 'procedural';
  }
  return 'na';
}

export function buildRigReports(publicDir: string = PUBLIC_DIR): RigReportRow[] {
  return RIG_INVENTORY.map((rig) => {
    const shippedClipNames = rig.glb ? readGlbClipNames(rig.glb, publicDir) : [];
    const clips = rig.expectedClips.map((clip) => {
      const shipped = shippedClipNames.includes(clip.name);
      return {
        clip,
        presence: resolvePresence(clip, shipped, rig.role),
        status: resolveClipStatus(clip, shipped),
      };
    });
    return { clips, rig, shippedClipNames };
  });
}

const STATUS_ICON: Record<ClipBacklog, string> = {
  complete: '✅',
  missing: '❌',
  revision: '🔧',
  unused: '💤',
};

function formatClipCell(row: ClipReportRow): string {
  const icon = STATUS_ICON[row.status];
  if (row.presence === 'procedural') {
    return `${icon} ${row.clip.name} _(procedural)_`;
  }
  if (row.status === 'unused') {
    return `${icon} ${row.clip.name} _(unused)_`;
  }
  if (row.status === 'complete') {
    return `${icon} ${row.clip.name}`;
  }
  return `${icon} ${row.clip.name}`;
}

function epicPriorityBadge(priority: string): string {
  return `\`${priority}\``;
}

export function buildMarkdownReport(publicDir: string = PUBLIC_DIR): string {
  const reports = buildRigReports(publicDir);
  const openEpicIds = [
    ...new Set(RIG_INVENTORY.map((rig) => rig.epicId).filter((id) => id !== 'complete')),
  ];

  const lines: string[] = [
    '## Character animation inventory',
    '',
    '_Generated by `yarn animation-clip-report`. Update [`characterAnimationInventory.ts`](../src/rendering/3d/CharacterScene/characterAnimationInventory.ts) when clip contracts change._',
    '',
    '### Epic backlog',
    '',
    '| Epic | Priority | Open rigs | Summary |',
    '| --- | --- | ---: | --- |',
  ];

  for (const epicId of openEpicIds.sort()) {
    const epic = ANIMATION_EPICS[epicId as AnimationEpicId];
    const openRigs = reports.filter((row) => row.rig.epicId === epicId);
    lines.push(
      `| **${epic.title}** | ${epicPriorityBadge(epic.priority)} | ${openRigs.length} | ${epic.summary} |`
    );
  }

  lines.push('', '### Rig matrix', '');

  for (const epicId of ['complete', ...openEpicIds.sort()] as const) {
    const epicRows = reports.filter((row) => row.rig.epicId === epicId);
    if (epicRows.length === 0) continue;

    const heading =
      epicId === 'complete'
        ? 'Complete / reference rigs'
        : ANIMATION_EPICS[epicId as AnimationEpicId].title;
    lines.push(`#### ${heading}`, '');
    lines.push('| Rig | GLB | Idle | Attack | Hit | Defeat | Other | Notes |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- | --- |');

    for (const { clips, rig, shippedClipNames } of epicRows) {
      const byName = Object.fromEntries(clips.map((row) => [row.clip.name, row]));
      const cell = (name: string) => (byName[name] ? formatClipCell(byName[name]) : '—');

      const otherClips = clips.filter(
        (row) => !['Idle', 'Attack', 'Hit', 'Defeat', 'Empty'].includes(row.clip.name)
      );
      const other =
        otherClips.length > 0
          ? otherClips.map((row) => formatClipCell(row)).join('<br>')
          : shippedClipNames
              .filter(
                (name) =>
                  !rig.expectedClips.some((clip) => clip.name === name) &&
                  !['Idle', 'Attack', 'Hit', 'Defeat'].includes(name)
              )
              .map((name) => `💤 ${name} _(unexpected)_`)
              .join('<br>') || '—';

      const idleCell =
        byName['Idle'] != null
          ? cell('Idle')
          : byName['Empty'] != null
            ? cell('Empty')
            : rig.expectedClips
                .filter((clip) => clip.kind === 'idle-switch' || clip.kind === 'transition')
                .map((clip) => formatClipCell(byName[clip.name]))
                .join('<br>') || '—';

      lines.push(
        `| ${rig.displayName} | \`${rig.glb ?? '—'}\` | ${idleCell} | ${cell('Attack')} | ${cell('Hit')} | ${cell('Defeat')} | ${other} | ${rig.notes ?? ''} |`
      );
    }

    lines.push('');
  }

  const missingCount = reports
    .flatMap((row) => row.clips)
    .filter((clip) => clip.status === 'missing').length;
  lines.push(
    '---',
    '',
    `**Totals:** ${RIG_INVENTORY.length} tracked rigs · ${missingCount} clips marked missing · ${reports.filter((row) => row.rig.epicId === 'complete').length} reference-complete rigs`
  );

  return lines.join('\n');
}

export function countMissingClips(publicDir: string = PUBLIC_DIR): number {
  return buildRigReports(publicDir)
    .flatMap((row) => row.clips)
    .filter((clip) => clip.status === 'missing').length;
}
